### ISSUE TITLE
Unable to log in or upload images

### ISSUE THREAD

**Issue by qingmuhy744** [andrii-kryvoviaz/slink#29]
Unable to log in or upload images, the error message is as follows
```shell
2024-11-08 00:13:03,975 INFO Included extra file "/etc/supervisor/conf.d/production.conf" during parsing
2024-11-08 00:13:03,981 INFO Set uid to user 0 succeeded
2024-11-08 00:13:04,018 INFO RPC interface 'supervisor' initialized
2024-11-08 00:13:04,021 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-11-08 00:13:04,022 INFO supervisord started with pid 1
2024-11-08 00:13:05,029 INFO spawned: 'client-app' with pid 7
2024-11-08 00:13:05,040 INFO spawned: 'redis' with pid 8
2024-11-08 00:13:05,057 INFO spawned: 'startup' with pid 9
2024-11-08 00:13:05,070 INFO spawned: 'swoole-runtime' with pid 10
2024-11-08 00:13:05,089 INFO spawned: 'symfony_about' with pid 12
2024-11-08 00:13:05,163 INFO success: startup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2024-11-08 00:13:06,205 INFO success: client-app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-11-08 00:13:06,206 INFO success: redis entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-11-08 00:13:06,206 INFO success: swoole-runtime entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-11-08 00:13:06,207 INFO success: symfony_about entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Listening on 0.0.0.0:3000
 -------------------- ------------------------------------
  Symfony
 -------------------- ------------------------------------
  Version              7.1.4
  Long-Term Support    No
  End of maintenance   01/2025 (in +84 days)
  End of life          01/2025 (in +84 days)
 -------------------- ------------------------------------
  Kernel
 -------------------- ------------------------------------
  Type                 Slink\Shared\Infrastructure\Kernel
  Environment          prod
  Debug                false
  Charset              UTF-8
  Cache directory      ./var/cache/prod (882 KiB)
  Build directory      ./var/cache/prod (882 KiB)
  Log directory        ./var/log (0 B)
 -------------------- ------------------------------------
  PHP
 -------------------- ------------------------------------
  Version              8.3.11
  Architecture         64 bits
  Intl locale          en_US_POSIX
  Timezone             UTC (2024-11-08T00:13:09+00:00)
  OPcache              true
  APCu                 false
  Xdebug               false
 -------------------- ------------------------------------


 [OK] Already at the latest version
      ("Slink\Shared\Infrastructure\Persistence\EventStore\Migrations\Version202
      31029174455")


 [OK] Already at the latest version
      ("Slink\Shared\Infrastructure\Persistence\Doctrine\Migrations\Version20240
      916221937")


 [OK] Done!

2024-11-08 00:13:11,705 INFO exited: startup (exit status 0; expected)
[2024-11-08 00:13:18 *31.0]     WARNING Context::compress(): Unknown compression method
[2024-11-08 00:13:19 *31.0]     WARNING Context::compress(): Unknown compression method
TypeError: Cannot convert argument to a ByteString because the character at index 58 has a value of 21018 which is greater than 255.
    at webidl.converters.ByteString (node:internal/deps/undici/undici:1685:17)
    at _Headers.append (node:internal/deps/undici/undici:1932:35)
    at file:///app/svelte-kit/server/chunks/index3-BJKS-9sK.js:95:15
    at Array.forEach (<anonymous>)
    at getResponseWithCookies (file:///app/svelte-kit/server/chunks/index3-BJKS-9sK.js:89:20)
    at file:///app/svelte-kit/server/chunks/hooks.server-Cg3SZk8K.js:120:12
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async respond (file:///app/svelte-kit/server/index.js:3859:22)
    at async Array.ssr (file:///app/svelte-kit/handler.js:1272:3)
```

**Comment by andrii-kryvoviaz** [comment]
Can you provide more details on how to reproduce the issue, as well as the environment and configuration you are using?

**Comment by qingmuhy744** [comment]
After my watchtower automatically upgraded my image, this issue was magically fixed automatically, I'm very sorry, I can't reproduce the bug now.

## Environment

I am running a Debian 12 system with Caddy as a reverse proxy, and the final distribution is handled through Cloudflare CDN.

For reference, here is my `docker-compose` file setup that I used:



~~~yaml
slink:
  image: anirdev/slink:latest
  container_name: slink
  restart: unless-stopped
  environment:
    # Your application hostname
    - ORIGIN=https://i.example.com
    
    # Require user approval before they can upload images
    - USER_APPROVAL_REQUIRED=true
    
    # User password requirements
    - USER_PASSWORD_MIN_LENGTH=8
    - USER_PASSWORD_REQUIREMENTS=15 # bitmask of requirements 
    
    # Maximum image size allowed to be uploaded (no more than 50M)
    - IMAGE_MAX_SIZE=15M
    
    # Storage provider to use. 
    # Available options are local and smb
    - STORAGE_PROVIDER=local
  volumes:
    # Persist the database
    - ./slink/var/data:/app/var/data
    # Persist the uploaded images
    - ./slink/images:/app/slink/images
  ports:
    # Expose the application on port 3000
    - "3000:3000"
~~~
